### ISSUE TITLE
1.18.2 backport?

### ISSUE THREAD

**Issue by justlukie** [I-No-oNe/Glowing-entities#1]

**Comment by I-No-oNe** [comment]
@the-just-luke Can u try the mod please on 1.18?(I think it should work there)

**Comment by uhb217** [comment]
@the-just-luke You can try it on 1.18.2, and if it doesn’t work, tell us, and we will create a new version for 1.18.2

**Comment by I-No-oNe** [comment]
@uhb217 the mod isn't working on 1.18.2, the fabric api changed there, we will need to make another version 😭

**Comment by I-No-oNe** [comment]
> @the-just-luke and @uhb217, I added a 1.18.2! 
> **if there any problems please Dm me or open here an issue.**
